// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated with protocol_gen.go -- do not edit this file.
//   go run scripts/protocol_gen/protocol_gen.go
//
// DAP version 1.68.0

#ifndef dap_converters_h
#define dap_converters_h
#include <string>
#include "dap/protocol.h"
#include "dap/session.h"
#include "dap/traits.h"

namespace dap {

struct ServerCaps {
  bool columnsStartAt1 = true;
  bool linesStartAt1 = true;
  bool pathsAreURIs = false;

  bool convertColumns = true;
  bool convertLines = true;
  bool convertStackFrameLineAndColumnWhenSourceDoesntExist = true;
  bool convertSourcePaths = true;
  bool convertSourceOrigins = true;
};

inline string PathToUri(const string& p) {
  if (p.empty()) {
    return p;
  }
  string path = p;
  std::transform(path.begin(), path.end(), path.begin(), [](char c) {
    if (c == '\\') {
      return '/';
    }
    return c;
  });
  return "file://" + path;
}

inline string UriToPath(const string& uri) {
  if (uri.empty()) {
    return uri;
  }
  std::string path;
  for (char c : uri) {
    if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
        (c >= '0' && c <= '9') || c == '+' || c == '/' || c == ':' ||
        c == '.' || c == '-' || c == '_' || c == '~' || c > '\xFF') {
      path += c;
    } else if (c == '\\') {
      path += '/';
    } else {
      path += "%" + std::to_string(static_cast<int>(c));
    }
  }
  return path;
}

static string ConvertPathToClient(const string& path,
                                  const InitializeRequest& clientCaps,
                                  const ServerCaps& serverCaps) {
  bool clientPathsAreURIs = clientCaps.pathFormat.value("path") == "uri";
  if (serverCaps.pathsAreURIs == clientPathsAreURIs) {
    return path;
  }
  if (clientPathsAreURIs) {
    return PathToUri(path);
  }
  return UriToPath(path);
}

static string ConvertPathToServer(const string& path,
                                  const InitializeRequest& clientCaps,
                                  const ServerCaps& serverCaps) {
  bool clientPathsAreURIs = clientCaps.pathFormat.value("path") == "uri";
  if (serverCaps.pathsAreURIs == clientPathsAreURIs) {
    return path;
  }
  if (clientPathsAreURIs) {
    return UriToPath(path);
  }
  return PathToUri(path);
}

inline integer ConvertLineToServer(integer line,
                                   const InitializeRequest& clientCaps,
                                   const ServerCaps& serverCaps) {
  if (!serverCaps.convertLines) {
    return line;
  }
  if (serverCaps.linesStartAt1 == clientCaps.linesStartAt1.value(true)) {
    return line;
  }
  if (serverCaps.linesStartAt1) {
    return line + 1;
  }
  return line - 1;
}

inline integer ConvertColumnToServer(integer column,
                                     const InitializeRequest& clientCaps,
                                     const ServerCaps& serverCaps) {
  if (!serverCaps.convertColumns) {
    return column;
  }
  if (serverCaps.columnsStartAt1 == clientCaps.columnsStartAt1.value(true)) {
    return column;
  }
  if (serverCaps.columnsStartAt1) {
    return column + 1;
  }
  return column - 1;
}

inline integer ConvertLineToClient(integer line,
                                   const InitializeRequest& clientCaps,
                                   const ServerCaps& serverCaps) {
  if (!serverCaps.convertLines) {
    return line;
  }
  if (serverCaps.linesStartAt1 == clientCaps.linesStartAt1.value(true)) {
    return line;
  }
  if (serverCaps.linesStartAt1) {
    return line - 1;
  }
  return line + 1;
}

inline integer ConvertColumnToClient(integer column,
                                     const InitializeRequest& clientCaps,
                                     const ServerCaps& serverCaps) {
  if (!serverCaps.convertColumns) {
    return column;
  }
  if (serverCaps.columnsStartAt1 == clientCaps.columnsStartAt1.value(true)) {
    return column;
  }
  if (serverCaps.columnsStartAt1) {
    return column - 1;
  }
  return column + 1;
}

template <typename T, typename Enable = void>
struct request_converter {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& caps) {
    // do nothing
  }
};

template <typename T, typename Enable = void>
struct response_converter {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& caps) {
    // do nothing
  }
};

template <typename T, typename Enable = void>
struct event_converter {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& caps) {
    // do nothing
  }
};

// special functions for converting Source objects
static void ConvertSourceToClient(Source& source,
                                  const InitializeRequest& clientCaps,
                                  const ServerCaps& caps) {
  if (!caps.convertSourcePaths && !caps.convertSourceOrigins) {
    return;
  }
  if (caps.convertSourcePaths && source.path.has_value()) {
    source.path = ConvertPathToClient(source.path.value(), clientCaps, caps);
  }
  if (caps.convertSourceOrigins && source.origin.has_value()) {
    source.origin =
        ConvertPathToClient(source.origin.value(), clientCaps, caps);
  }
  if (source.sources.has_value()) {
    for (auto& source : source.sources.value()) {
      ConvertSourceToClient(source, clientCaps, caps);
    }
  }
}

static void ConvertSourceToServer(Source& source,
                                  const InitializeRequest& clientCaps,
                                  const ServerCaps& caps) {
  if (!caps.convertSourcePaths && !caps.convertSourceOrigins) {
    return;
  }
  if (caps.convertSourcePaths && source.path.has_value()) {
    source.path = ConvertPathToServer(source.path.value(), clientCaps, caps);
  }
  if (caps.convertSourceOrigins && source.origin.has_value()) {
    source.origin =
        ConvertPathToServer(source.origin.value(), clientCaps, caps);
  }
  if (source.sources.has_value()) {
    for (auto& source : source.sources.value()) {
      ConvertSourceToServer(source, clientCaps, caps);
    }
  }
}

// special function for converting StackFrame objects
inline StackFrame ConvertStackFrameToClient(StackFrame& stackFrame,
                                            const InitializeRequest& clientCaps,
                                            const ServerCaps& caps) {
  if (stackFrame.source.has_value() &&
      (caps.convertSourcePaths || caps.convertSourceOrigins)) {
    ConvertSourceToClient(stackFrame.source.value(), clientCaps, caps);
  }
  /* special handling for non-optional line and column; due to the ambiguity of
  the spec regarding this:
          // The line within the source of the frame. If the source attribute is
  missing
          // or doesn't exist, 'line' is 0 and should be ignored by the client.
  We only convert it if the source exists */
  if (caps.convertStackFrameLineAndColumnWhenSourceDoesntExist ||
      (stackFrame.source.has_value())) {
    if (caps.convertLines) {
      stackFrame.line = ConvertLineToServer(stackFrame.line, clientCaps, caps);
    }
    if (caps.convertColumns) {
      stackFrame.column =
          ConvertColumnToServer(stackFrame.column, clientCaps, caps);
    }
  }
  if (stackFrame.endColumn.has_value() && caps.convertColumns) {
    stackFrame.endColumn =
        ConvertColumnToServer(stackFrame.endColumn.value(), clientCaps, caps);
  }
  if (stackFrame.endLine.has_value() && caps.convertLines) {
    stackFrame.endLine =
        ConvertLineToServer(stackFrame.endLine.value(), clientCaps, caps);
  }
  return stackFrame;
}
// no need to convert StackFrame objects to server since the client doesn't send
// them

inline Breakpoint ConvertBreakpointToClient(Breakpoint& obj,
                                            const InitializeRequest& clientCaps,
                                            const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToClient(obj.column.value(), clientCaps, serverCaps);
  }
  if (obj.endColumn.has_value()) {
    obj.endColumn =
        ConvertColumnToClient(obj.endColumn.value(), clientCaps, serverCaps);
  }
  if (obj.endLine.has_value()) {
    obj.endLine =
        ConvertLineToClient(obj.endLine.value(), clientCaps, serverCaps);
  }
  if (obj.line.has_value()) {
    obj.line = ConvertLineToClient(obj.line.value(), clientCaps, serverCaps);
  }
  if (obj.source.has_value()) {
    ConvertSourceToClient(obj.source.value(), clientCaps, serverCaps);
  }
  return obj;
}

inline Breakpoint ConvertBreakpointToServer(Breakpoint& obj,
                                            const InitializeRequest& clientCaps,
                                            const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToServer(obj.column.value(), clientCaps, serverCaps);
  }
  if (obj.endColumn.has_value()) {
    obj.endColumn =
        ConvertColumnToServer(obj.endColumn.value(), clientCaps, serverCaps);
  }
  if (obj.endLine.has_value()) {
    obj.endLine =
        ConvertLineToServer(obj.endLine.value(), clientCaps, serverCaps);
  }
  if (obj.line.has_value()) {
    obj.line = ConvertLineToServer(obj.line.value(), clientCaps, serverCaps);
  }
  if (obj.source.has_value()) {
    ConvertSourceToServer(obj.source.value(), clientCaps, serverCaps);
  }
  return obj;
}

template <typename T>
struct event_converter<T, traits::EnableIfIsType<BreakpointEvent, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    ConvertBreakpointToClient(obj.breakpoint, clientCaps, serverCaps);
  }
};

inline BreakpointLocation ConvertBreakpointLocationToClient(
    BreakpointLocation& obj,
    const InitializeRequest& clientCaps,
    const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToClient(obj.column.value(), clientCaps, serverCaps);
  }
  if (obj.endColumn.has_value()) {
    obj.endColumn =
        ConvertColumnToClient(obj.endColumn.value(), clientCaps, serverCaps);
  }
  if (obj.endLine.has_value()) {
    obj.endLine =
        ConvertLineToClient(obj.endLine.value(), clientCaps, serverCaps);
  }
  obj.line = ConvertLineToClient(obj.line, clientCaps, serverCaps);

  return obj;
}

inline BreakpointLocation ConvertBreakpointLocationToServer(
    BreakpointLocation& obj,
    const InitializeRequest& clientCaps,
    const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToServer(obj.column.value(), clientCaps, serverCaps);
  }
  if (obj.endColumn.has_value()) {
    obj.endColumn =
        ConvertColumnToServer(obj.endColumn.value(), clientCaps, serverCaps);
  }
  if (obj.endLine.has_value()) {
    obj.endLine =
        ConvertLineToServer(obj.endLine.value(), clientCaps, serverCaps);
  }
  obj.line = ConvertLineToServer(obj.line, clientCaps, serverCaps);

  return obj;
}

template <typename T>
struct response_converter<
    T,
    traits::EnableIfIsType<BreakpointLocationsResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    for (auto& item : obj.breakpoints) {
      ConvertBreakpointLocationToClient(item, clientCaps, serverCaps);
    }
  }
};

template <typename T>
struct request_converter<
    T,
    traits::EnableIfIsType<BreakpointLocationsRequest, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    if (obj.column.has_value()) {
      obj.column =
          ConvertColumnToServer(obj.column.value(), clientCaps, serverCaps);
    }
    if (obj.endColumn.has_value()) {
      obj.endColumn =
          ConvertColumnToServer(obj.endColumn.value(), clientCaps, serverCaps);
    }
    if (obj.endLine.has_value()) {
      obj.endLine =
          ConvertLineToServer(obj.endLine.value(), clientCaps, serverCaps);
    }
    obj.line = ConvertLineToServer(obj.line, clientCaps, serverCaps);

    ConvertSourceToServer(obj.source, clientCaps, serverCaps);
  }
};

template <typename T>
struct request_converter<T, traits::EnableIfIsType<CompletionsRequest, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    obj.column = ConvertColumnToServer(obj.column, clientCaps, serverCaps);

    if (obj.line.has_value()) {
      obj.line = ConvertLineToServer(obj.line.value(), clientCaps, serverCaps);
    }
  }
};

inline DisassembledInstruction ConvertDisassembledInstructionToClient(
    DisassembledInstruction& obj,
    const InitializeRequest& clientCaps,
    const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToClient(obj.column.value(), clientCaps, serverCaps);
  }
  if (obj.endColumn.has_value()) {
    obj.endColumn =
        ConvertColumnToClient(obj.endColumn.value(), clientCaps, serverCaps);
  }
  if (obj.endLine.has_value()) {
    obj.endLine =
        ConvertLineToClient(obj.endLine.value(), clientCaps, serverCaps);
  }
  if (obj.line.has_value()) {
    obj.line = ConvertLineToClient(obj.line.value(), clientCaps, serverCaps);
  }
  if (obj.location.has_value()) {
    ConvertSourceToClient(obj.location.value(), clientCaps, serverCaps);
  }
  return obj;
}

inline DisassembledInstruction ConvertDisassembledInstructionToServer(
    DisassembledInstruction& obj,
    const InitializeRequest& clientCaps,
    const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToServer(obj.column.value(), clientCaps, serverCaps);
  }
  if (obj.endColumn.has_value()) {
    obj.endColumn =
        ConvertColumnToServer(obj.endColumn.value(), clientCaps, serverCaps);
  }
  if (obj.endLine.has_value()) {
    obj.endLine =
        ConvertLineToServer(obj.endLine.value(), clientCaps, serverCaps);
  }
  if (obj.line.has_value()) {
    obj.line = ConvertLineToServer(obj.line.value(), clientCaps, serverCaps);
  }
  if (obj.location.has_value()) {
    ConvertSourceToServer(obj.location.value(), clientCaps, serverCaps);
  }
  return obj;
}

template <typename T>
struct response_converter<T, traits::EnableIfIsType<DisassembleResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    for (auto& item : obj.instructions) {
      ConvertDisassembledInstructionToClient(item, clientCaps, serverCaps);
    }
  }
};

template <typename T>
struct request_converter<T, traits::EnableIfIsType<EvaluateRequest, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    if (obj.column.has_value()) {
      obj.column =
          ConvertColumnToServer(obj.column.value(), clientCaps, serverCaps);
    }
    if (obj.line.has_value()) {
      obj.line = ConvertLineToServer(obj.line.value(), clientCaps, serverCaps);
    }
    if (obj.source.has_value()) {
      ConvertSourceToServer(obj.source.value(), clientCaps, serverCaps);
    }
  }
};

inline GotoTarget ConvertGotoTargetToClient(GotoTarget& obj,
                                            const InitializeRequest& clientCaps,
                                            const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToClient(obj.column.value(), clientCaps, serverCaps);
  }
  if (obj.endColumn.has_value()) {
    obj.endColumn =
        ConvertColumnToClient(obj.endColumn.value(), clientCaps, serverCaps);
  }
  if (obj.endLine.has_value()) {
    obj.endLine =
        ConvertLineToClient(obj.endLine.value(), clientCaps, serverCaps);
  }
  obj.line = ConvertLineToClient(obj.line, clientCaps, serverCaps);

  return obj;
}

inline GotoTarget ConvertGotoTargetToServer(GotoTarget& obj,
                                            const InitializeRequest& clientCaps,
                                            const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToServer(obj.column.value(), clientCaps, serverCaps);
  }
  if (obj.endColumn.has_value()) {
    obj.endColumn =
        ConvertColumnToServer(obj.endColumn.value(), clientCaps, serverCaps);
  }
  if (obj.endLine.has_value()) {
    obj.endLine =
        ConvertLineToServer(obj.endLine.value(), clientCaps, serverCaps);
  }
  obj.line = ConvertLineToServer(obj.line, clientCaps, serverCaps);

  return obj;
}

template <typename T>
struct response_converter<T, traits::EnableIfIsType<GotoTargetsResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    for (auto& item : obj.targets) {
      ConvertGotoTargetToClient(item, clientCaps, serverCaps);
    }
  }
};

template <typename T>
struct request_converter<T, traits::EnableIfIsType<GotoTargetsRequest, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    if (obj.column.has_value()) {
      obj.column =
          ConvertColumnToServer(obj.column.value(), clientCaps, serverCaps);
    }
    obj.line = ConvertLineToServer(obj.line, clientCaps, serverCaps);

    ConvertSourceToServer(obj.source, clientCaps, serverCaps);
  }
};

template <typename T>
struct event_converter<T, traits::EnableIfIsType<LoadedSourceEvent, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    ConvertSourceToClient(obj.source, clientCaps, serverCaps);
  }
};

template <typename T>
struct response_converter<T, traits::EnableIfIsType<LoadedSourcesResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    for (auto& item : obj.sources) {
      ConvertSourceToClient(item, clientCaps, serverCaps);
    }
  }
};

template <typename T>
struct response_converter<T, traits::EnableIfIsType<LocationsResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    if (obj.column.has_value()) {
      obj.column =
          ConvertColumnToClient(obj.column.value(), clientCaps, serverCaps);
    }
    if (obj.endColumn.has_value()) {
      obj.endColumn =
          ConvertColumnToClient(obj.endColumn.value(), clientCaps, serverCaps);
    }
    if (obj.endLine.has_value()) {
      obj.endLine =
          ConvertLineToClient(obj.endLine.value(), clientCaps, serverCaps);
    }
    obj.line = ConvertLineToClient(obj.line, clientCaps, serverCaps);

    ConvertSourceToClient(obj.source, clientCaps, serverCaps);
  }
};

template <typename T>
struct event_converter<T, traits::EnableIfIsType<OutputEvent, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    if (obj.column.has_value()) {
      obj.column =
          ConvertColumnToClient(obj.column.value(), clientCaps, serverCaps);
    }
    if (obj.line.has_value()) {
      obj.line = ConvertLineToClient(obj.line.value(), clientCaps, serverCaps);
    }
    if (obj.source.has_value()) {
      ConvertSourceToClient(obj.source.value(), clientCaps, serverCaps);
    }
  }
};

inline Scope ConvertScopeToClient(Scope& obj,
                                  const InitializeRequest& clientCaps,
                                  const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToClient(obj.column.value(), clientCaps, serverCaps);
  }
  if (obj.endColumn.has_value()) {
    obj.endColumn =
        ConvertColumnToClient(obj.endColumn.value(), clientCaps, serverCaps);
  }
  if (obj.endLine.has_value()) {
    obj.endLine =
        ConvertLineToClient(obj.endLine.value(), clientCaps, serverCaps);
  }
  if (obj.line.has_value()) {
    obj.line = ConvertLineToClient(obj.line.value(), clientCaps, serverCaps);
  }
  if (obj.source.has_value()) {
    ConvertSourceToClient(obj.source.value(), clientCaps, serverCaps);
  }
  return obj;
}

inline Scope ConvertScopeToServer(Scope& obj,
                                  const InitializeRequest& clientCaps,
                                  const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToServer(obj.column.value(), clientCaps, serverCaps);
  }
  if (obj.endColumn.has_value()) {
    obj.endColumn =
        ConvertColumnToServer(obj.endColumn.value(), clientCaps, serverCaps);
  }
  if (obj.endLine.has_value()) {
    obj.endLine =
        ConvertLineToServer(obj.endLine.value(), clientCaps, serverCaps);
  }
  if (obj.line.has_value()) {
    obj.line = ConvertLineToServer(obj.line.value(), clientCaps, serverCaps);
  }
  if (obj.source.has_value()) {
    ConvertSourceToServer(obj.source.value(), clientCaps, serverCaps);
  }
  return obj;
}

template <typename T>
struct response_converter<T, traits::EnableIfIsType<ScopesResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    for (auto& item : obj.scopes) {
      ConvertScopeToClient(item, clientCaps, serverCaps);
    }
  }
};

template <typename T>
struct response_converter<T,
                          traits::EnableIfIsType<SetBreakpointsResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    for (auto& item : obj.breakpoints) {
      ConvertBreakpointToClient(item, clientCaps, serverCaps);
    }
  }
};

inline SourceBreakpoint ConvertSourceBreakpointToClient(
    SourceBreakpoint& obj,
    const InitializeRequest& clientCaps,
    const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToClient(obj.column.value(), clientCaps, serverCaps);
  }
  obj.line = ConvertLineToClient(obj.line, clientCaps, serverCaps);

  return obj;
}

inline SourceBreakpoint ConvertSourceBreakpointToServer(
    SourceBreakpoint& obj,
    const InitializeRequest& clientCaps,
    const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToServer(obj.column.value(), clientCaps, serverCaps);
  }
  obj.line = ConvertLineToServer(obj.line, clientCaps, serverCaps);

  return obj;
}

template <typename T>
struct request_converter<T, traits::EnableIfIsType<SetBreakpointsRequest, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    if (obj.breakpoints.has_value()) {
      for (auto& item : obj.breakpoints.value()) {
        ConvertSourceBreakpointToServer(item, clientCaps, serverCaps);
      }
    }
    ConvertSourceToServer(obj.source, clientCaps, serverCaps);
  }
};

template <typename T>
struct response_converter<
    T,
    traits::EnableIfIsType<SetDataBreakpointsResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    for (auto& item : obj.breakpoints) {
      ConvertBreakpointToClient(item, clientCaps, serverCaps);
    }
  }
};

template <typename T>
struct response_converter<
    T,
    traits::EnableIfIsType<SetExceptionBreakpointsResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    if (obj.breakpoints.has_value()) {
      for (auto& item : obj.breakpoints.value()) {
        ConvertBreakpointToClient(item, clientCaps, serverCaps);
      }
    }
  }
};

template <typename T>
struct response_converter<
    T,
    traits::EnableIfIsType<SetFunctionBreakpointsResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    for (auto& item : obj.breakpoints) {
      ConvertBreakpointToClient(item, clientCaps, serverCaps);
    }
  }
};

template <typename T>
struct response_converter<
    T,
    traits::EnableIfIsType<SetInstructionBreakpointsResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    for (auto& item : obj.breakpoints) {
      ConvertBreakpointToClient(item, clientCaps, serverCaps);
    }
  }
};

template <typename T>
struct request_converter<T, traits::EnableIfIsType<SourceRequest, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    if (obj.source.has_value()) {
      ConvertSourceToServer(obj.source.value(), clientCaps, serverCaps);
    }
  }
};

template <typename T>
struct response_converter<T, traits::EnableIfIsType<StackTraceResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    for (auto& item : obj.stackFrames) {
      ConvertStackFrameToClient(item, clientCaps, serverCaps);
    }
  }
};

inline StepInTarget ConvertStepInTargetToClient(
    StepInTarget& obj,
    const InitializeRequest& clientCaps,
    const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToClient(obj.column.value(), clientCaps, serverCaps);
  }
  if (obj.endColumn.has_value()) {
    obj.endColumn =
        ConvertColumnToClient(obj.endColumn.value(), clientCaps, serverCaps);
  }
  if (obj.endLine.has_value()) {
    obj.endLine =
        ConvertLineToClient(obj.endLine.value(), clientCaps, serverCaps);
  }
  if (obj.line.has_value()) {
    obj.line = ConvertLineToClient(obj.line.value(), clientCaps, serverCaps);
  }
  return obj;
}

inline StepInTarget ConvertStepInTargetToServer(
    StepInTarget& obj,
    const InitializeRequest& clientCaps,
    const ServerCaps& serverCaps) {
  if (obj.column.has_value()) {
    obj.column =
        ConvertColumnToServer(obj.column.value(), clientCaps, serverCaps);
  }
  if (obj.endColumn.has_value()) {
    obj.endColumn =
        ConvertColumnToServer(obj.endColumn.value(), clientCaps, serverCaps);
  }
  if (obj.endLine.has_value()) {
    obj.endLine =
        ConvertLineToServer(obj.endLine.value(), clientCaps, serverCaps);
  }
  if (obj.line.has_value()) {
    obj.line = ConvertLineToServer(obj.line.value(), clientCaps, serverCaps);
  }
  return obj;
}

template <typename T>
struct response_converter<T, traits::EnableIfIsType<StepInTargetsResponse, T>> {
  void convert(T& obj,
               const InitializeRequest& clientCaps,
               const ServerCaps& serverCaps) {
    for (auto& item : obj.targets) {
      ConvertStepInTargetToClient(item, clientCaps, serverCaps);
    }
  }
};

inline bool IsConversionNecessary(const InitializeRequest& clientCaps,
                                  const ServerCaps& serverCaps) {
  if (!serverCaps.convertSourcePaths && !serverCaps.convertSourceOrigins &&
      !serverCaps.convertLines && !serverCaps.convertColumns) {
    return false;
  }
  if ((serverCaps.pathsAreURIs ==
       (clientCaps.pathFormat.value("path") == "uri")) &&
      (serverCaps.linesStartAt1 == clientCaps.linesStartAt1.value(true)) &&
      (serverCaps.columnsStartAt1 == clientCaps.columnsStartAt1.value(true))) {
    return false;
  }
  return true;
}

template <typename T>
struct response_converter<ResponseOrError<T>, traits::EnableIfIsType<ResponseOrError<T>, T>>{
	void convert(ResponseOrError<T>& obj,
		const InitializeRequest& clientCaps,
		const ServerCaps& serverCaps) {
			if (obj.error.has_value()){
				return;
			}
			response_converter<T>{}.convert(obj.response, clientCaps, serverCaps);
	}
};

template <typename T>
void ConvertRequestToServer(T& obj,
                            const InitializeRequest& clientCaps,
                            const ServerCaps& serverCaps) {
  if (!IsConversionNecessary(clientCaps, serverCaps)) {
    return;
  }
  request_converter<T> converter;
  converter.convert(obj, clientCaps, serverCaps);
}

template <typename T>
void ConvertResponseToClient(T& obj,
                             const InitializeRequest& clientCaps,
                             const ServerCaps& serverCaps) {
  if (!IsConversionNecessary(clientCaps, serverCaps)) {
    return;
  }
  response_converter<T> converter;
  converter.convert(obj, clientCaps, serverCaps);
}

template <typename T>
void ConvertEventToClient(T& obj,
                          const InitializeRequest& clientCaps,
                          const ServerCaps& serverCaps) {
  if (!IsConversionNecessary(clientCaps, serverCaps)) {
    return;
  }
  event_converter<T> converter;
  converter.convert(obj, clientCaps, serverCaps);
}

template <typename T>
[[nodiscard]] T ConvertRequestToServer(T&& obj,
                            const InitializeRequest& clientCaps,
                            const ServerCaps& serverCaps) {
  if (!IsConversionNecessary(clientCaps, serverCaps)) {
    return std::move(obj);
  }
  request_converter<T> converter;
  converter.convert(obj, clientCaps, serverCaps);
	return obj;
}

template <typename T>
[[nodiscard]] T ConvertResponseToClient(T&& obj,
                             const InitializeRequest& clientCaps,
                             const ServerCaps& serverCaps) {
  if (!IsConversionNecessary(clientCaps, serverCaps)) {
    return std::move(obj);
  }
  response_converter<T> converter;
  converter.convert(obj, clientCaps, serverCaps);
	return obj;
}

template <typename T>
[[nodiscard]] T ConvertEventToClient(T&& obj,
                          const InitializeRequest& clientCaps,
                          const ServerCaps& serverCaps) {
  if (!IsConversionNecessary(clientCaps, serverCaps)) {
    return std::move(obj);
  }
  event_converter<T> converter;
  converter.convert(obj, clientCaps, serverCaps);
	return obj;
}
}  // namespace dap
#endif  // dap_converters_h
